stages:
  - production

backend:
  image: alpine:3.13.4
  stage: production
  script:
    - apk add ruby-dev python3
    - gem install dpl
    - cd backend && pip3 install -r requirements.txt
    - dpl --provider=heroku --app=happyfishcardgame --api-key=$HEROKU_API_KEY
  only:
    - master

# Frontend deployed automatically on merge with master with Netlify
