stages:
  - production

backend:
  image: starefossen/ruby-node:latest
  stage: production
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev python3 python3-dev python3-pip
    - gem install dpl
    - cd backend && pip3 install -r requirements.txt
    - dpl --provider=heroku --app=happyfishcardgame --api-key=$HEROKU_API_KEY
  only:
    - master

# Frontend deployed automatically on merge with master with Netlify
